title: VDJ Sequence Dependence
description: > # this means to ignore newlines until "baseurl:"
  'This website is an online repository for the manuscript "
  Probing the Sequence-Dependent Dynamics of Endogenous and Synthetic RSSs in
  V(D)J Recombination'
permalink: 
baseurl: "/VDJ" # "/" # the subpath of your site, e.g. /blog
url: "http://rpgroup.caltech.edu" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings

author-img: logo.png # add your photo
social-github: RPGroup-PBoC # add your Github handle

# Tracker
# analytics: 

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "data_files"]
